const express=require('express');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const app=express();
app.disable('x-powered-by');
app.use(express.json({limit:'20kb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');next()});
app.use(express.static(path.join(__dirname,'public')));
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD;
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const SESSION_MS=1000*60*60*24*7;
const tokens=new Map();
const loginAttempts=new Map();
const clean=v=>String(v||'').trim();
const validPhone=p=>/^[+0-9 ()-]{7,25}$/.test(p);
const safeEqual=(a,b)=>{const aa=Buffer.from(String(a||'')),bb=Buffer.from(String(b||''));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb)};
const ipOf=req=>clean(req.headers['x-forwarded-for']).split(',')[0]||req.socket.remoteAddress||'unknown';
function prune(){const now=Date.now();for(const [t,exp] of tokens)if(exp<=now)tokens.delete(t);for(const [ip,a] of loginAttempts)if(now-a.first>15*60*1000)loginAttempts.delete(ip)}
setInterval(prune,15*60*1000).unref();
const auth=(req,res,next)=>{const t=(req.headers.authorization||'').replace('Bearer ','');const exp=tokens.get(t);if(!exp||exp<=Date.now()){if(t)tokens.delete(t);return res.status(401).json({error:'Please log in again'})}tokens.set(t,Date.now()+SESSION_MS);req.adminToken=t;next()};
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS slots(id SERIAL PRIMARY KEY,date DATE NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,venue TEXT NOT NULL,court TEXT NOT NULL,capacity INT NOT NULL DEFAULT 4,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS bookings(id SERIAL PRIMARY KEY,slot_id INT NOT NULL REFERENCES slots(id) ON DELETE CASCADE,name TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());ALTER TABLE slots ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';`);const {rows}=await pool.query('SELECT COUNT(*)::int AS n FROM slots');if(!rows[0].n){await pool.query(`INSERT INTO slots(date,start_time,end_time,venue,court,capacity) VALUES ('2026-09-29','16:30','17:30','Padel Dome','Court 1',4),('2026-09-29','17:30','18:30','Padel Dome','Court 1',4),('2026-09-29','18:30','19:30','Padel Dome','Court 1',4),('2026-09-29','19:30','20:30','Padel Dome','Court 1',4),('2026-10-01','10:00','11:00','Padel Dome','Court 2',4),('2026-10-01','18:00','19:00','Padel Dome','Court 2',4)`);const s=(await pool.query('SELECT id FROM slots ORDER BY id')).rows;await pool.query('INSERT INTO bookings(slot_id,name,phone) VALUES ($1,$2,$3),($4,$5,$6),($4,$7,$8),($4,$9,$10),($11,$12,$13)',[s[0].id,'Tracey','087 555 0142',s[2].id,'Tiago','087 555 0191','Gav','086 555 0134','Shivaun','085 555 0188',s[3].id,'David Morgan','087 555 0177']);}}
async function getSlots(privateView=false){const where=privateView?'':"WHERE s.status='active' AND (s.date > CURRENT_DATE OR (s.date=CURRENT_DATE AND s.end_time>CURRENT_TIME))";const {rows}=await pool.query(`SELECT s.id,to_char(s.date,'YYYY-MM-DD') date,to_char(s.start_time,'HH24:MI') start,to_char(s.end_time,'HH24:MI') end,s.venue,s.court,s.capacity,s.status,COALESCE(json_agg(json_build_object('id',b.id,'name',b.name,'phone',b.phone) ORDER BY b.id) FILTER (WHERE b.id IS NOT NULL),'[]') bookings FROM slots s LEFT JOIN bookings b ON b.slot_id=s.id ${where} GROUP BY s.id ORDER BY s.date,s.start_time`);return privateView?rows:rows.map(s=>({...s,bookings:s.bookings.map(b=>({name:b.name}))}));}
app.get('/api/slots',async(req,res)=>{try{res.setHeader('Cache-Control','no-store');res.json(await getSlots(false))}catch(e){console.error(e);res.status(500).json({error:'Could not load lessons'})}});
app.post('/api/book/:id',async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const s=(await client.query("SELECT * FROM slots WHERE id=$1 AND status='active' AND (date>CURRENT_DATE OR (date=CURRENT_DATE AND end_time>CURRENT_TIME)) FOR UPDATE",[req.params.id])).rows[0];if(!s){await client.query('ROLLBACK');return res.status(404).json({error:'Lesson is no longer available'})}const count=Number((await client.query('SELECT COUNT(*) FROM bookings WHERE slot_id=$1',[s.id])).rows[0].count);if(count>=s.capacity){await client.query('ROLLBACK');return res.status(409).json({error:'This lesson is full'})}const name=clean(req.body.name).slice(0,100),phone=clean(req.body.phone).slice(0,25);if(name.length<2||!validPhone(phone)){await client.query('ROLLBACK');return res.status(400).json({error:'Please enter a valid name and mobile number'})}await client.query('INSERT INTO bookings(slot_id,name,phone) VALUES($1,$2,$3)',[s.id,name,phone]);await client.query('COMMIT');const all=await getSlots(false);res.json(all.find(x=>x.id==s.id))}catch(e){await client.query('ROLLBACK');console.error(e);res.status(500).json({error:'Booking could not be saved'})}finally{client.release()}});
app.post('/api/admin/login',(req,res)=>{prune();const ip=ipOf(req),now=Date.now(),a=loginAttempts.get(ip)||{count:0,first:now,lockedUntil:0};if(a.lockedUntil>now)return res.status(429).json({error:'Too many login attempts. Please try again in 15 minutes.'});if(!ADMIN_PASSWORD||!safeEqual(req.body.password,ADMIN_PASSWORD)){if(now-a.first>15*60*1000){a.count=0;a.first=now}a.count++;if(a.count>=5)a.lockedUntil=now+15*60*1000;loginAttempts.set(ip,a);return res.status(401).json({error:'Incorrect password'})}loginAttempts.delete(ip);const token=crypto.randomBytes(32).toString('hex');tokens.set(token,now+SESSION_MS);res.setHeader('Cache-Control','no-store');res.json({token,expiresIn:SESSION_MS})});
app.post('/api/admin/logout',auth,(req,res)=>{tokens.delete(req.adminToken);res.json({ok:true})});
app.get('/api/admin/slots',auth,async(req,res)=>{try{res.setHeader('Cache-Control','no-store');res.json(await getSlots(true))}catch(e){res.status(500).json({error:'Could not load lessons'})}});
app.post('/api/admin/slots',auth,async(req,res)=>{try{const date=clean(req.body.date),venue=clean(req.body.venue).slice(0,100),court=clean(req.body.court).slice(0,60),times=req.body.times,duration=Number(req.body.duration||60),capacity=Number(req.body.capacity||4);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!venue||!court||!Array.isArray(times)||!times.length||![60,90].includes(duration)||capacity<1||capacity>4)return res.status(400).json({error:'Please check the lesson details'});for(const t of times){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(t))return res.status(400).json({error:'Invalid lesson time'});const [h,m]=t.split(':').map(Number),d=new Date(2000,0,1,h,m);d.setMinutes(d.getMinutes()+duration);const end=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;await pool.query('INSERT INTO slots(date,start_time,end_time,venue,court,capacity) VALUES($1,$2,$3,$4,$5,$6)',[date,t,end,venue,court,capacity])}res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Could not create lessons'})}});
app.post('/api/admin/slots/:id/bookings',auth,async(req,res)=>{try{const {rows}=await pool.query("SELECT capacity,status,(SELECT COUNT(*) FROM bookings WHERE slot_id=$1)::int booked FROM slots WHERE id=$1",[req.params.id]);if(!rows[0])return res.status(404).json({error:'Not found'});if(rows[0].status!=='active')return res.status(409).json({error:'This lesson is cancelled'});if(rows[0].booked>=rows[0].capacity)return res.status(409).json({error:'Lesson is full'});const name=clean(req.body.name).slice(0,100),phone=clean(req.body.phone).slice(0,25);if(name.length<2)return res.status(400).json({error:'Name is required'});if(phone&&!validPhone(phone))return res.status(400).json({error:'Please enter a valid mobile number'});await pool.query('INSERT INTO bookings(slot_id,name,phone) VALUES($1,$2,$3)',[req.params.id,name,phone]);res.json({ok:true})}catch(e){res.status(500).json({error:'Could not add player'})}});
app.post('/api/admin/slots/:id/cancel',auth,async(req,res)=>{try{const {rows}=await pool.query("UPDATE slots SET status='cancelled' WHERE id=$1 RETURNING id",[req.params.id]);if(!rows[0])return res.status(404).json({error:'Lesson not found'});res.json({ok:true})}catch(e){res.status(500).json({error:'Could not cancel lesson'})}});
app.delete('/api/admin/slots/:id/bookings/:i',auth,async(req,res)=>{try{const bookings=(await pool.query('SELECT id FROM bookings WHERE slot_id=$1 ORDER BY id',[req.params.id])).rows;const b=bookings[Number(req.params.i)];if(!b)return res.status(404).json({error:'Booking not found'});await pool.query('DELETE FROM bookings WHERE id=$1',[b.id]);res.json({ok:true})}catch(e){res.status(500).json({error:'Could not remove booking'})}});
app.get('/admin',(req,res)=>{res.setHeader('Cache-Control','no-store');res.sendFile(path.join(__dirname,'public','admin.html'))});
app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.send('ok')}catch(e){res.status(503).send('database unavailable')}});
app.use((req,res,next)=>{if(req.method!=='GET'||req.path.startsWith('/api/'))return next();res.sendFile(path.join(__dirname,'public','index.html'))});
const port=process.env.PORT||3000;init().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`Jose Padel Booking running on ${port}`))).catch(e=>{console.error('Database init failed',e);process.exit(1)});