const express=require('express');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const app=express();
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD;
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const tokens=new Set();
const auth=(req,res,next)=>{const t=(req.headers.authorization||'').replace('Bearer ','');if(!tokens.has(t))return res.status(401).json({error:'Please log in'});next()};
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS slots(id SERIAL PRIMARY KEY,date DATE NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,venue TEXT NOT NULL,court TEXT NOT NULL,capacity INT NOT NULL DEFAULT 4,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS bookings(id SERIAL PRIMARY KEY,slot_id INT NOT NULL REFERENCES slots(id) ON DELETE CASCADE,name TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());ALTER TABLE slots ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';`);const {rows}=await pool.query('SELECT COUNT(*)::int AS n FROM slots');if(!rows[0].n){await pool.query(`INSERT INTO slots(date,start_time,end_time,venue,court,capacity) VALUES ('2026-09-29','16:30','17:30','Padel Dome','Court 1',4),('2026-09-29','17:30','18:30','Padel Dome','Court 1',4),('2026-09-29','18:30','19:30','Padel Dome','Court 1',4),('2026-09-29','19:30','20:30','Padel Dome','Court 1',4),('2026-10-01','10:00','11:00','Padel Dome','Court 2',4),('2026-10-01','18:00','19:00','Padel Dome','Court 2',4)`);const s=(await pool.query('SELECT id FROM slots ORDER BY id')).rows;await pool.query('INSERT INTO bookings(slot_id,name,phone) VALUES ($1,$2,$3),($4,$5,$6),($4,$7,$8),($4,$9,$10),($11,$12,$13)',[s[0].id,'Tracey','087 555 0142',s[2].id,'Tiago','087 555 0191','Gav','086 555 0134','Shivaun','085 555 0188',s[3].id,'David Morgan','087 555 0177']);}}
async function getSlots(privateView=false){const where=privateView?'':'WHERE s.status=\'active\' AND (s.date > CURRENT_DATE OR (s.date=CURRENT_DATE AND s.end_time>CURRENT_TIME))';const {rows}=await pool.query(`SELECT s.id,to_char(s.date,'YYYY-MM-DD') date,to_char(s.start_time,'HH24:MI') start,to_char(s.end_time,'HH24:MI') end,s.venue,s.court,s.capacity,s.status,COALESCE(json_agg(json_build_object('id',b.id,'name',b.name,'phone',b.phone) ORDER BY b.id) FILTER (WHERE b.id IS NOT NULL),'[]') bookings FROM slots s LEFT JOIN bookings b ON b.slot_id=s.id ${where} GROUP BY s.id ORDER BY s.date,s.start_time`);return privateView?rows:rows.map(s=>({...s,bookings:s.bookings.map(b=>({name:b.name}))}));}
app.get('/api/slots',async(req,res)=>{try{res.json(await getSlots(false))}catch(e){console.error(e);res.status(500).json({error:'Could not load lessons'})}});
app.post('/api/book/:id',async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const s=(await client.query("SELECT * FROM slots WHERE id=$1 AND status='active' FOR UPDATE",[req.params.id])).rows[0];if(!s){await client.query('ROLLBACK');return res.status(404).json({error:'Lesson is no longer available'})}const count=Number((await client.query('SELECT COUNT(*) FROM bookings WHERE slot_id=$1',[s.id])).rows[0].count);if(count>=s.capacity){await client.query('ROLLBACK');return res.status(409).json({error:'This lesson is full'})}const name=String(req.body.name||'').trim(),phone=String(req.body.phone||'').trim();if(!name||!phone){await client.query('ROLLBACK');return res.status(400).json({error:'Name and mobile number are required'})}await client.query('INSERT INTO bookings(slot_id,name,phone) VALUES($1,$2,$3)',[s.id,name,phone]);await client.query('COMMIT');const all=await getSlots(false);res.json(all.find(x=>x.id==s.id))}catch(e){await client.query('ROLLBACK');console.error(e);res.status(500).json({error:'Booking could not be saved'})}finally{client.release()}});
app.post('/api/admin/login',(req,res)=>{if(!ADMIN_PASSWORD||req.body.password!==ADMIN_PASSWORD)return res.status(401).json({error:'Incorrect password'});const token=crypto.randomBytes(24).toString('hex');tokens.add(token);res.json({token})});
app.post('/api/admin/logout',auth,(req,res)=>{const t=(req.headers.authorization||'').replace('Bearer ','');tokens.delete(t);res.json({ok:true})});
app.get('/api/admin/slots',auth,async(req,res)=>{try{res.json(await getSlots(true))}catch(e){res.status(500).json({error:'Could not load lessons'})}});
app.post('/api/admin/slots',auth,async(req,res)=>{try{const {date,venue,court,times,duration=60,capacity=4}=req.body;if(!date||!venue||!court||!Array.isArray(times)||!times.length)return res.status(400).json({error:'Complete all fields and add at least one time'});for(const t of times){const [h,m]=t.split(':').map(Number),d=new Date(2000,0,1,h,m);d.setMinutes(d.getMinutes()+Number(duration));const end=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;await pool.query('INSERT INTO slots(date,start_time,end_time,venue,court,capacity) VALUES($1,$2,$3,$4,$5,$6)',[date,t,end,venue,court,Number(capacity)])}res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'Could not create lessons'})}});
app.post('/api/admin/slots/:id/bookings',auth,async(req,res)=>{try{const {rows}=await pool.query("SELECT capacity,status,(SELECT COUNT(*) FROM bookings WHERE slot_id=$1)::int booked FROM slots WHERE id=$1",[req.params.id]);if(!rows[0])return res.status(404).json({error:'Not found'});if(rows[0].status!=='active')return res.status(409).json({error:'This lesson is cancelled'});if(rows[0].booked>=rows[0].capacity)return res.status(409).json({error:'Lesson is full'});const name=String(req.body.name||'').trim(),phone=String(req.body.phone||'').trim();if(!name)return res.status(400).json({error:'Name is required'});await pool.query('INSERT INTO bookings(slot_id,name,phone) VALUES($1,$2,$3)',[req.params.id,name,phone]);res.json({ok:true})}catch(e){res.status(500).json({error:'Could not add player'})}});
app.post('/api/admin/slots/:id/cancel',auth,async(req,res)=>{try{const {rows}=await pool.query("UPDATE slots SET status='cancelled' WHERE id=$1 RETURNING id",[req.params.id]);if(!rows[0])return res.status(404).json({error:'Lesson not found'});res.json({ok:true})}catch(e){res.status(500).json({error:'Could not cancel lesson'})}});
app.delete('/api/admin/slots/:id',auth,async(req,res)=>{try{await pool.query('DELETE FROM slots WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({error:'Could not delete lesson'})}});
app.delete('/api/admin/slots/:id/bookings/:i',auth,async(req,res)=>{try{const bookings=(await pool.query('SELECT id FROM bookings WHERE slot_id=$1 ORDER BY id',[req.params.id])).rows;const b=bookings[Number(req.params.i)];if(!b)return res.status(404).json({error:'Booking not found'});await pool.query('DELETE FROM bookings WHERE id=$1',[b.id]);res.json({ok:true})}catch(e){res.status(500).json({error:'Could not remove booking'})}});
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.send('ok')}catch(e){res.status(503).send('database unavailable')}});app.use((req,res,next)=>{if(req.method!=='GET'||req.path.startsWith('/api/'))return next();res.sendFile(path.join(__dirname,'public','index.html'))});const port=process.env.PORT||3000;init().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`Jose Padel Booking running on ${port}`))).catch(e=>{console.error('Database init failed',e);process.exit(1)});